### ISSUE TITLE
Alternate camera platforms

### ISSUE THREAD

**Issue by jamesd256** [openPupil/Open-PupilEXT#1]
Hi,

Congratulations on a spectacular project, very inspiring.

What are your thoughts on supporting other camera platforms.  There seem to be a few other solutions with similar spec to Basler for as little as one quarter the price.

I am very poor, but would like to be able to try out your amazing software.   I am very willing to take on the work. just trying to get a sense of how much effort you think it would be.

I hope this is the right channel to reach you to discuss such things.

Thanks & regards,

James

**Comment by BZandi** [comment]
Thanks! Happy to hear that you find our project of value.

Generally, we use an abstract camera class [camera.h](https://github.com/openPupil/Open-PupilEXT/blob/main/PupilEXT/src/devices/camera.h), which is used in the [singleCamera.cpp](https://github.com/openPupil/Open-PupilEXT/blob/main/PupilEXT/src/devices/singleCamera.cpp) and [stereoCamera.cpp](https://github.com/openPupil/Open-PupilEXT/blob/main/PupilEXT/src/devices/stereoCamera.cpp) file to retrieve the images. Additional camera platforms can be easly integrated by preparing the files in the device folder (see [PupilEXT/src/devices](https://github.com/openPupil/Open-PupilEXT/tree/main/PupilEXT/src/devices)).

Note that consumer webcams are not suited for the program structure in PupilEXT as we use an event-handler to grab the images from the camera (see [singleCameraImageEventHandler.cpp](https://github.com/openPupil/Open-PupilEXT/blob/main/PupilEXT/src/devices/singleCameraImageEventHandler.cpp)). There are also additional features that can not be used with webcams, such as stereo camera recording because we applied a hardware trigger to synchronise the two cameras, which is impossible with webcams. Additionally, with webcams, there some numerous issues that need to be solved for accurate pupil measurements. Thus, it is recommended that the alternative camera brands offer machine vision cameras, i.e. industrial cameras with a C++ camera library. 

If you want to run PupilEXT with very low investment, you have three options:

a) Take a look at the Basler dart series. They are affordable (~120 Euro) and should work with PupilEXT (not tested), as they use the Pylon library, which we use in PupilEXT to interface the camera(s). Link: https://www.baslerweb.com/en/products/cameras/area-scan-cameras/dart/

b) If you want to go even cheaper, you need to use a webcam (< 100 Euro). As mentioned, it is hard to integrate webcams in PupilEXT for real-time measurements, as we use an event handler to distribute the image inside the functions of PupilEXT. An alternative would be to record the images with an external tool and load the images into PupilEXT for offline analysis. We provide demo images that you can already use for offline analysis and testing the software. For this, download the demo dataset in section 2.4 (see readme file) and check out the respective video tutorial for offline analysis in which we load externally acquired images into PupilEXT. Link: https://vimeo.com/564778587

c) We are working on a Python version (library) of PupilEXT, which we publish later this year. With the Python library, you will be able to integrate any camera that you like.
